/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#1a221a",
        "primary": "#8bd5be",
        "on-tertiary-fixed-variant": "#304c45",
        "on-primary-container": "#8bd5be",
        "tertiary-fixed": "#cae9df",
        "on-secondary-fixed-variant": "#314f00",
        "on-surface": "#dce5d9",
        "surface-tint": "#8bd5be",
        "on-surface-variant": "#bec9c4",
        "inverse-surface": "#dce5d9",
        "outline": "#89938e",
        "on-primary": "#00382c",
        "error": "#ffb4ab",
        "background": "#0d150f",
        "surface-container-low": "#161d16",
        "surface-dim": "#0d150f",
        "surface-container-highest": "#2f372f",
        "on-error": "#690005",
        "on-tertiary-container": "#aecdc3",
        "inverse-primary": "#1b6a57",
        "secondary-fixed-dim": "#9ad93d",
        "error-container": "#93000a",
        "surface-bright": "#333b33",
        "primary-container": "#045e4c",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#2a322b",
        "primary-fixed": "#a7f1d9",
        "on-secondary-fixed": "#112000",
        "tertiary-container": "#3c5850",
        "tertiary-fixed-dim": "#aecdc3",
        "surface-variant": "#2f372f",
        "secondary-fixed": "#b4f657",
        "surface-container-lowest": "#08100a",
        "secondary-container": "#6ea900",
        "surface-container-high": "#242c24",
        "on-primary-fixed": "#002019",
        "on-tertiary-fixed": "#03201a",
        "outline-variant": "#3f4945",
        "secondary": "#9ad93d",
        "surface": "#0d150f",
        "on-secondary": "#213600",
        "tertiary": "#aecdc3",
        "on-background": "#dce5d9",
        "on-secondary-container": "#213700",
        "on-primary-fixed-variant": "#005141",
        "primary-fixed-dim": "#8bd5be",
        "on-tertiary": "#19352f"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "sm": "12px",
        "gutter": "24px",
        "margin-desktop": "64px",
        "margin-mobile": "16px",
        "md": "24px",
        "base": "8px",
        "lg": "48px",
        "xl": "80px",
        "xs": "4px"
      },
      fontFamily: {
        "label-sm": ["Space Grotesk"],
        "headline-md": ["Space Grotesk"],
        "display-lg": ["Space Grotesk"],
        "display-lg-mobile": ["Space Grotesk"],
        "label-md": ["Space Grotesk"],
        "headline-lg": ["Space Grotesk"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "500"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "display-lg": ["64px", {"lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "display-lg-mobile": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
