/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#e8f5e1",
        "primary": "#045e4c",
        "on-tertiary-fixed-variant": "#045e4c",
        "on-primary-container": "#f6fff3",
        "tertiary-fixed": "#99d83c",
        "on-secondary-fixed-variant": "#045e4c",
        "on-surface": "#045e4c",
        "surface-tint": "#045e4c",
        "on-surface-variant": "#0a735e",
        "inverse-surface": "#045e4c",
        "outline": "#99d83c",
        "on-primary": "#f6fff3",
        "error": "#ba1a1a",
        "background": "#f6fff3",
        "surface-container-low": "#f6fff3",
        "surface-dim": "#e8f5e1",
        "surface-container-highest": "#d5ebd0",
        "on-error": "#ffffff",
        "on-tertiary-container": "#f6fff3",
        "inverse-primary": "#99d83c",
        "secondary-fixed-dim": "#99d83c",
        "error-container": "#ffdad6",
        "surface-bright": "#f6fff3",
        "primary-container": "#045e4c",
        "on-error-container": "#410002",
        "inverse-on-surface": "#f6fff3",
        "primary-fixed": "#045e4c",
        "on-secondary-fixed": "#045e4c",
        "tertiary-container": "#99d83c",
        "tertiary-fixed-dim": "#99d83c",
        "surface-variant": "#e8f5e1",
        "secondary-fixed": "#99d83c",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#99d83c",
        "surface-container-high": "#e8f5e1",
        "on-primary-fixed": "#f6fff3",
        "on-tertiary-fixed": "#f6fff3",
        "outline-variant": "#99d83c",
        "secondary": "#99d83c",
        "surface": "#f6fff3",
        "on-secondary": "#045e4c",
        "tertiary": "#99d83c",
        "on-background": "#045e4c",
        "on-secondary-container": "#045e4c",
        "on-primary-fixed-variant": "#f6fff3",
        "primary-fixed-dim": "#045e4c",
        "on-tertiary": "#045e4c"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "sm": "12px",
        "gutter": "24px",
        "margin-desktop": "64px",
        "margin-mobile": "16px",
        "md": "24px",
        "base": "8px",
        "lg": "48px",
        "xl": "80px",
        "xs": "4px"
      },
      fontFamily: {
        "label-sm": ["Space Grotesk"],
        "headline-md": ["Space Grotesk"],
        "display-lg": ["Space Grotesk"],
        "display-lg-mobile": ["Space Grotesk"],
        "label-md": ["Space Grotesk"],
        "headline-lg": ["Space Grotesk"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "500"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "display-lg": ["64px", {"lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "display-lg-mobile": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
